### ISSUE TITLE
Countdown Module

### ISSUE THREAD

**Issue by liomj** [mambax7/countdown2#1]
Hi, Mamba I have forked this countdown2 module of yours
https://github.com/liomj/countdown2

my progress so far..im not very good at programming but i followed by examples
heres what i made so far
Event List
![eventlist](https://user-images.githubusercontent.com/16532279/81495740-01961300-92e5-11ea-8eae-76b023d27cab.jpg)
Event View
![eventview](https://user-images.githubusercontent.com/16532279/81495744-078bf400-92e5-11ea-8156-5a86878f4dac.jpg)
Block 
![block](https://user-images.githubusercontent.com/16532279/81495748-14104c80-92e5-11ea-9169-2eddfb0a94ec.jpg)

currently some problem and error im stucked with that i would need help on
- automatic uploads/countdown folder creation
- Event Category - Fetching Category Name in block, event list and event view
- Comment for event view is not working

can anyone out there help ?

**Comment by mambax7** [comment]
That looks AWESOME!!!! 
I'll take a look sometimes next week. 
But please post in the Module Testing Area and ask for help there:
https://xoops.org/modules/newbb/viewforum.php?forum=66
