### ISSUE TITLE
Warning: constant(): Couldn't find constant COUNTDOWN_AUTHOR_LOGOIMG 

### ISSUE THREAD

**Issue by liomj** [mambax7/countdown2#12]
Warning: constant(): Couldn't find constant COUNTDOWN_AUTHOR_LOGOIMG in file /modules/countdown/config/config.php line 79

**Comment by mambax7** [comment]
Can you add labels to issues, like here would be a "bug"? Or is it not visible to you? 

![image](https://user-images.githubusercontent.com/613686/82512102-1771b800-9add-11ea-950e-d44f5584f49f.png)

**Comment by mambax7** [comment]
It should be now fixed in https://github.com/mambax7/countdown/commit/37e99f257477d091d48a0fa2e82f5ad4880ca0e5
