### ISSUE TITLE
Block - select event to display

### ISSUE THREAD

**Issue by liomj** [mambax7/countdown2#14]
is not working properly..

1. selection is not selected when editing the block
2. need to change categoryid to categoryname

**Comment by liomj** [comment]
![Uploading Untitled.jpg…]()

**Comment by mambax7** [comment]
Can you tell me more about the issue? Maybe a screenshot? 
Where should the categoryid  be changed to categoryname?

**Comment by liomj** [comment]
![e](https://user-images.githubusercontent.com/16532279/82632579-3716f680-9c2b-11ea-8179-824327c1043c.jpg)

a. now its showing category id instead of category name in the drop down
b. when editing the block the  last selected value of the drop down is not selected



![xoops](https://user-images.githubusercontent.com/16532279/82632832-f4095300-9c2b-11ea-8713-ee2e732f50fc.jpg)
