### ISSUE TITLE
Links in profile area not working

### ISSUE THREAD

**Issue by Heyula** [mambax7/countdown2#26]
Hi @liomj

Links in profile area not working

![1](https://user-images.githubusercontent.com/5504159/139579969-66362e4e-50ed-4725-9c72-c723dd4e0c85.jpg)
![2](https://user-images.githubusercontent.com/5504159/139579970-f3d21b69-4409-4552-9f58-aa0c6f621379.jpg)
![3](https://user-images.githubusercontent.com/5504159/139579972-28c13d7c-217d-40fc-8bff-d1416d5279ba.jpg)
![4](https://user-images.githubusercontent.com/5504159/139579973-b1b71ad3-2144-453b-a9e2-5586bf4fc495.png)

https://xoops.erenyumak.com/modules/countdown/

**Comment by ggoffy** [comment]
hi. can you please test https://github.com/ggoffy/countdown

**Comment by Heyula** [comment]
@ggoffy 
Thanks for correcting the error.

**Comment by liomj** [comment]
thank you @ggoffy
