### ISSUE TITLE
Missing countdown, strange display of date

### ISSUE THREAD

**Issue by mambax7** [mambax7/countdown2#28]
I just installed it, and it shows some strange display. 
I didn't look into it, because maybe somebody is aware of it? 
![image](https://user-images.githubusercontent.com/613686/140470581-ed6895c2-7a99-44a0-8046-88cf8ba10db6.png)

<html><body>

XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.25
MySQL Version | 5.7.36

</body>
</html>

**Comment by mambax7** [comment]
It seems like there is an issue with the Smarty "data_format" 

Once I commented out from the template:
```
|date_format:"%A, %B %e %Y %l:%M %p"
```
it looks better:
![image](https://user-images.githubusercontent.com/613686/140474529-3dddbf7e-4beb-46b4-aac5-9b89fe8dc136.png)

But the counter itself is still not working!

**Comment by liomj** [comment]
i just installed in localhost wamp, seems working to me
![Webex](https://user-images.githubusercontent.com/16532279/140479796-1883bdd5-3312-429f-b91a-ccb40a887fce.jpg)

<html><body>


XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.24
MySQL Version | 5.5.5-10.4.21-MariaDB


</body>
</html>

**Comment by mambax7** [comment]
Can you do a fresh installation with the code on GitHub?  Maybe you have some additional libraries/files that I'm missing? Or is it specific to a theme that you have? 
Could you test it on the regular xBootstrap theme?

**Comment by liomj** [comment]
I dont have access to my machine right now, ill try again later

the last time i was using the xswatch4 dark mode theme

**Comment by liomj** [comment]
> Can you do a fresh installation with the code on GitHub? Maybe you have some additional libraries/files that I'm missing? Or is it specific to a theme that you have? Could you test it on the regular xBootstrap theme?

i have made fresh installation and using xbootstrap theme and sample data and its working fine
![Untitled](https://user-images.githubusercontent.com/16532279/140670713-2c8102b4-69cf-4b0a-af3c-42b6c35770cb.jpg)

**Comment by mambax7** [comment]
Thanks for checking. 
So I did now a fresh installation of XOOPS and the module, and while this time it shows the numbers, they are wrong:  the first event is scheduled for Nov. 30th, but it shows only 5 hours away:
![image](https://user-images.githubusercontent.com/613686/140672971-03af67d8-c95e-4f16-b2dd-3eee37635aab.png)

And the same with the 2022 event:
![image](https://user-images.githubusercontent.com/613686/140673035-879726f8-2b9d-45ae-b17e-994fa13a006f.png)

So something strange is going on...

**Comment by mambax7** [comment]
The test data seems to be OK:
![image](https://user-images.githubusercontent.com/613686/140673156-8913c4a1-eb41-4e2c-8c87-17449a01f945.png)

**Comment by mambax7** [comment]
I have also installed it right now on our demo/test server, and it's the same:
http://demo.xoops.org/modules/countdown/

![image](https://user-images.githubusercontent.com/613686/140674539-7f762d57-092f-4fba-8802-a68112d6a7bd.png)

**Comment by mambax7** [comment]
FYI - I've used the latest files directly from the repository: https://github.com/XOOPS/XoopsCore25

So if you used some previous XOOPS files, then maybe the new files are causing problems and we need to fix them, because they introduced some bugs that you just helped to discover ?

**Comment by liomj** [comment]
> FYI - I've used the latest files directly from the repository: https://github.com/XOOPS/XoopsCore25
> 
> So if you used some previous XOOPS files, then maybe the new files are causing problems and we need to fix them, because they introduced some bugs that you just helped to discover ?  

I didnt use any previous xoops file
i downloaded the latest xoops and countdown from github

And made the fresh 
installation..

**Comment by mambax7** [comment]
So if XOOPS and Countdown are the same, then the different must me on the server or the browser? 
I tried our Demo page in different browsers:

- Chrome: wrong
- Firefox: wrong
- Edge: wrong
- Opera: wrong
- Brave: wrong

But on **Tor** it was correct:
![image](https://user-images.githubusercontent.com/613686/140676189-700cc1e1-3d12-4f89-8ae7-c4ad42ccb25b.png)

But Tor is redirecting through different countries, and my IP showed that I'm "from Switzerland", so it seems like the Countdown shows correctly for some countries (like the European countries using the European date format), but not for the US date format.

**Comment by mambax7** [comment]
Hmm, would it possible that there is a conflict between how using date formats in Smarty? 
In one place you use `data_format` like this:
```
starttime="<{$smarty.now|date_format:"%Y-%m-%d %H:%M:%S"}>"
endtime="<{$events.dateiso}>"
```
and in another:
`<{$events.date|date_format:"%A, %B %e %Y %l:%M %p"}>`

According to [Smarty's date_format](https://www.smarty.net/docs/en/language.modifier.date.format.tpl), these are for current locale:

```
%A - full weekday name according to the current locale 
%B - full month name according to the current locale
```
and maybe the "current local" works fine with the `<{$events.dateiso}>` when it is in Europe , but has a conflict when it is in the US? 
This is just a wild guess, as I'm definitely not an expert in JavaScript and in Smarty :) 

But when I see that the same site works when is tested in Europe, but fails when it is in the US, then it seems a plausible guess...

**Comment by mambax7** [comment]
OK, the problems seems to be with JavaScript and not with Smarty - every time that I refresh, the remaining time to the event resets to 5 hours, which is the time difference between my local time and GMT

So somehow, instead of keeping the "event time" and calculating the remaining time for it, it switches to the GMT time and shows 5 hours remaining
![image](https://user-images.githubusercontent.com/613686/140690549-188580e5-b876-457f-9d19-499369403f86.png)

**Comment by mambax7** [comment]
@liomj You might be OK in your testing because you're GMT+ while we're GMT-
Can you check your calculation formula to accommodate for it?

**Comment by liomj** [comment]
yes im in GMT+8

>  Can you check your calculation formula to accommodate for it?

How do i check this ?

**Comment by mambax7** [comment]
Fixed in: https://github.com/XoopsModules25x/countdown/pull/29

**Comment by mambax7** [comment]
FYI: the issues was that Countdown was pulling the start time directly from Smarty via `$smarty.now`, which was providing a GMT time.
Once I pulled the local time from PHP from the user directly (via `time()`), then it is working now. 

![image](https://user-images.githubusercontent.com/613686/140716264-a752bc10-eb2e-4cab-8514-7f3e116b02a7.png)
