### ISSUE TITLE
automatic uploads/countdown folder creation

### ISSUE THREAD

**Issue by liomj** [mambax7/countdown2#5]
it does not create the folder automatically on install

**Comment by mambax7** [comment]
See if this commit solved that for you: https://github.com/mambax7/countdown2/commit/50c635e9d1d296038748f8553e5f2bb69d41dd44

**Comment by liomj** [comment]
Thank you Mamba. yes now uploads/countdown2 is created oninstall

but it create another problem when creating event

Warning: opendir(/uploads/countdown/images/,/uploads/countdown/images/): The system cannot find the path specified. (code: 3) in file /class/xoopslists.php line 177
--
Warning: opendir(/uploads/countdown/images/): failed to open dir: No such file or directory in file /class/xoopslists.php line 177

**Comment by mambax7** [comment]
I just uploaded a fix. 
 
This is only a temporary fix, as we'll have to replace with a variable that
contains the name of the module folder.  

  _____

**Comment by liomj** [comment]
Thank you. Issue can be close
